{{- if eq .Release.Namespace "kube-system" }}
apiVersion: v1
kind: RoleBinding
metadata:
  name: system:image-builders
roleRef:
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: builder
groupNames: null
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:builder
{{- end }}
