{{- if .Values.clusterAdmin }}
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: tiller-cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: {{ .Release.Namespace }}
roleRef:
  name: cluster-admin
{{- end }}
