{{- if eq .Release.Namespace "kube-system" }}
apiVersion: v1
kind: RoleBinding
metadata:
  name: system:image-pullers
roleRef:
  name: system:image-puller
subjects:
- kind: SystemGroup
  name: system:serviceaccounts:{{ .Release.Namespace }}
groupNames:
- system:serviceaccounts:{{ .Release.Namespace }}
userNames: null
{{- end }}
